/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as MarketingRouteRouteImport } from './routes/_marketing/route'
import { Route as HomeRouteRouteImport } from './routes/home/route'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthSetupRouteImport } from './routes/_auth/setup'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as MarketingAboutRouteImport } from './routes/_marketing/about'
import { Route as MarketingFeaturesRouteImport } from './routes/_marketing/features'
import { Route as MarketingStatusRouteImport } from './routes/_marketing/status'
import { Route as ApiStatusRouteImport } from './routes/api/status'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as HomeProfileRouteImport } from './routes/home/profile'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as HomeUsersIndexRouteImport } from './routes/home/users/index'
import { Route as HomeUsersCreateRouteImport } from './routes/home/users/create'
import { Route as HomeUsersUserIdEditRouteImport } from './routes/home/users/$userId.edit'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRouteRoute = MarketingRouteRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRouteRoute = HomeRouteRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSetupRoute = AuthSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const MarketingAboutRoute = MarketingAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const MarketingFeaturesRoute = MarketingFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const MarketingStatusRoute = MarketingStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const ApiStatusRoute = ApiStatusRouteImport.update({
  id: '/api/status',
  path: '/api/status',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeProfileRoute = HomeProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => HomeRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeUsersIndexRoute = HomeUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeUsersCreateRoute = HomeUsersCreateRouteImport.update({
  id: '/users/create',
  path: '/users/create',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeUsersUserIdEditRoute = HomeUsersUserIdEditRouteImport.update({
  id: '/users/$userId/edit',
  path: '/users/$userId/edit',
  getParentRoute: () => HomeRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/home': typeof HomeRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/setup': typeof AuthSetupRoute
  '/about': typeof MarketingAboutRoute
  '/features': typeof MarketingFeaturesRoute
  '/status': typeof MarketingStatusRoute
  '/api/status': typeof ApiStatusRoute
  '/home/profile': typeof HomeProfileRoute
  '/home/': typeof HomeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/home/users/create': typeof HomeUsersCreateRoute
  '/home/users/': typeof HomeUsersIndexRoute
  '/home/users/$userId/edit': typeof HomeUsersUserIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof MarketingIndexRoute
  '/login': typeof AuthLoginRoute
  '/setup': typeof AuthSetupRoute
  '/about': typeof MarketingAboutRoute
  '/features': typeof MarketingFeaturesRoute
  '/status': typeof MarketingStatusRoute
  '/api/status': typeof ApiStatusRoute
  '/home/profile': typeof HomeProfileRoute
  '/home': typeof HomeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/home/users/create': typeof HomeUsersCreateRoute
  '/home/users': typeof HomeUsersIndexRoute
  '/home/users/$userId/edit': typeof HomeUsersUserIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_marketing': typeof MarketingRouteRouteWithChildren
  '/home': typeof HomeRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/setup': typeof AuthSetupRoute
  '/_marketing/about': typeof MarketingAboutRoute
  '/_marketing/features': typeof MarketingFeaturesRoute
  '/_marketing/status': typeof MarketingStatusRoute
  '/api/status': typeof ApiStatusRoute
  '/home/profile': typeof HomeProfileRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/home/': typeof HomeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/home/users/create': typeof HomeUsersCreateRoute
  '/home/users/': typeof HomeUsersIndexRoute
  '/home/users/$userId/edit': typeof HomeUsersUserIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/login'
    | '/setup'
    | '/about'
    | '/features'
    | '/status'
    | '/api/status'
    | '/home/profile'
    | '/home/'
    | '/api/auth/$'
    | '/home/users/create'
    | '/home/users/'
    | '/home/users/$userId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/setup'
    | '/about'
    | '/features'
    | '/status'
    | '/api/status'
    | '/home/profile'
    | '/home'
    | '/api/auth/$'
    | '/home/users/create'
    | '/home/users'
    | '/home/users/$userId/edit'
  id:
    | '__root__'
    | '/_auth'
    | '/_marketing'
    | '/home'
    | '/_auth/login'
    | '/_auth/setup'
    | '/_marketing/about'
    | '/_marketing/features'
    | '/_marketing/status'
    | '/api/status'
    | '/home/profile'
    | '/_marketing/'
    | '/home/'
    | '/api/auth/$'
    | '/home/users/create'
    | '/home/users/'
    | '/home/users/$userId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  MarketingRouteRoute: typeof MarketingRouteRouteWithChildren
  HomeRouteRoute: typeof HomeRouteRouteWithChildren
  ApiStatusRoute: typeof ApiStatusRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/setup': {
      id: '/_auth/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthSetupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/about': {
      id: '/_marketing/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MarketingAboutRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/features': {
      id: '/_marketing/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof MarketingFeaturesRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/status': {
      id: '/_marketing/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof MarketingStatusRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/api/status': {
      id: '/api/status'
      path: '/api/status'
      fullPath: '/api/status'
      preLoaderRoute: typeof ApiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/profile': {
      id: '/home/profile'
      path: '/profile'
      fullPath: '/home/profile'
      preLoaderRoute: typeof HomeProfileRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/users/': {
      id: '/home/users/'
      path: '/users'
      fullPath: '/home/users/'
      preLoaderRoute: typeof HomeUsersIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/users/create': {
      id: '/home/users/create'
      path: '/users/create'
      fullPath: '/home/users/create'
      preLoaderRoute: typeof HomeUsersCreateRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/users/$userId/edit': {
      id: '/home/users/$userId/edit'
      path: '/users/$userId/edit'
      fullPath: '/home/users/$userId/edit'
      preLoaderRoute: typeof HomeUsersUserIdEditRouteImport
      parentRoute: typeof HomeRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSetupRoute: typeof AuthSetupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSetupRoute: AuthSetupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface MarketingRouteRouteChildren {
  MarketingAboutRoute: typeof MarketingAboutRoute
  MarketingFeaturesRoute: typeof MarketingFeaturesRoute
  MarketingStatusRoute: typeof MarketingStatusRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteRouteChildren: MarketingRouteRouteChildren = {
  MarketingAboutRoute: MarketingAboutRoute,
  MarketingFeaturesRoute: MarketingFeaturesRoute,
  MarketingStatusRoute: MarketingStatusRoute,
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteRouteWithChildren = MarketingRouteRoute._addFileChildren(
  MarketingRouteRouteChildren,
)

interface HomeRouteRouteChildren {
  HomeProfileRoute: typeof HomeProfileRoute
  HomeIndexRoute: typeof HomeIndexRoute
  HomeUsersCreateRoute: typeof HomeUsersCreateRoute
  HomeUsersIndexRoute: typeof HomeUsersIndexRoute
  HomeUsersUserIdEditRoute: typeof HomeUsersUserIdEditRoute
}

const HomeRouteRouteChildren: HomeRouteRouteChildren = {
  HomeProfileRoute: HomeProfileRoute,
  HomeIndexRoute: HomeIndexRoute,
  HomeUsersCreateRoute: HomeUsersCreateRoute,
  HomeUsersIndexRoute: HomeUsersIndexRoute,
  HomeUsersUserIdEditRoute: HomeUsersUserIdEditRoute,
}

const HomeRouteRouteWithChildren = HomeRouteRoute._addFileChildren(
  HomeRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  MarketingRouteRoute: MarketingRouteRouteWithChildren,
  HomeRouteRoute: HomeRouteRouteWithChildren,
  ApiStatusRoute: ApiStatusRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
