/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as MarketingRouteRouteImport } from './routes/_marketing/route'
import { Route as HomeRouteRouteImport } from './routes/home/route'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as MarketingAboutRouteImport } from './routes/_marketing/about'
import { Route as MarketingFeaturesRouteImport } from './routes/_marketing/features'
import { Route as MarketingStatusRouteImport } from './routes/_marketing/status'
import { Route as ApiStatusRouteImport } from './routes/api/status'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as HomeAchievementsRouteImport } from './routes/home/achievements'
import { Route as HomeCheckinsRouteImport } from './routes/home/checkins'
import { Route as HomeInsightsRouteImport } from './routes/home/insights'
import { Route as HomeProfileRouteImport } from './routes/home/profile'
import { Route as HomeSettingsRouteImport } from './routes/home/settings'
import { Route as HomeStreaksRouteImport } from './routes/home/streaks'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as HomeCirclesIndexRouteImport } from './routes/home/circles/index'
import { Route as HomeCirclesCircleIdRouteRouteImport } from './routes/home/circles/$circleId/route'
import { Route as HomeCirclesNewRouteImport } from './routes/home/circles/new'
import { Route as HomeHabitsIndexRouteImport } from './routes/home/habits/index'
import { Route as HomeHabitsHabitIdRouteRouteImport } from './routes/home/habits/$habitId/route'
import { Route as HomeHabitsArchivedRouteImport } from './routes/home/habits/archived'
import { Route as HomeHabitsNewRouteImport } from './routes/home/habits/new'
import { Route as HomeCirclesCircleIdIndexRouteImport } from './routes/home/circles/$circleId/index'
import { Route as HomeCirclesCircleIdEditRouteImport } from './routes/home/circles/$circleId/edit'
import { Route as HomeCirclesJoinCodeRouteImport } from './routes/home/circles/join.$code'
import { Route as HomeHabitsHabitIdIndexRouteImport } from './routes/home/habits/$habitId/index'
import { Route as HomeHabitsHabitIdEditRouteImport } from './routes/home/habits/$habitId/edit'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRouteRoute = MarketingRouteRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRouteRoute = HomeRouteRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const MarketingAboutRoute = MarketingAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const MarketingFeaturesRoute = MarketingFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const MarketingStatusRoute = MarketingStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const ApiStatusRoute = ApiStatusRouteImport.update({
  id: '/api/status',
  path: '/api/status',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeAchievementsRoute = HomeAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeCheckinsRoute = HomeCheckinsRouteImport.update({
  id: '/checkins',
  path: '/checkins',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeInsightsRoute = HomeInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeProfileRoute = HomeProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeSettingsRoute = HomeSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeStreaksRoute = HomeStreaksRouteImport.update({
  id: '/streaks',
  path: '/streaks',
  getParentRoute: () => HomeRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeCirclesIndexRoute = HomeCirclesIndexRouteImport.update({
  id: '/circles/',
  path: '/circles/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeCirclesCircleIdRouteRoute =
  HomeCirclesCircleIdRouteRouteImport.update({
    id: '/circles/$circleId',
    path: '/circles/$circleId',
    getParentRoute: () => HomeRouteRoute,
  } as any)
const HomeCirclesNewRoute = HomeCirclesNewRouteImport.update({
  id: '/circles/new',
  path: '/circles/new',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeHabitsIndexRoute = HomeHabitsIndexRouteImport.update({
  id: '/habits/',
  path: '/habits/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeHabitsHabitIdRouteRoute = HomeHabitsHabitIdRouteRouteImport.update({
  id: '/habits/$habitId',
  path: '/habits/$habitId',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeHabitsArchivedRoute = HomeHabitsArchivedRouteImport.update({
  id: '/habits/archived',
  path: '/habits/archived',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeHabitsNewRoute = HomeHabitsNewRouteImport.update({
  id: '/habits/new',
  path: '/habits/new',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeCirclesCircleIdIndexRoute =
  HomeCirclesCircleIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => HomeCirclesCircleIdRouteRoute,
  } as any)
const HomeCirclesCircleIdEditRoute = HomeCirclesCircleIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => HomeCirclesCircleIdRouteRoute,
} as any)
const HomeCirclesJoinCodeRoute = HomeCirclesJoinCodeRouteImport.update({
  id: '/circles/join/$code',
  path: '/circles/join/$code',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeHabitsHabitIdIndexRoute = HomeHabitsHabitIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeHabitsHabitIdRouteRoute,
} as any)
const HomeHabitsHabitIdEditRoute = HomeHabitsHabitIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => HomeHabitsHabitIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/home': typeof HomeRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/about': typeof MarketingAboutRoute
  '/features': typeof MarketingFeaturesRoute
  '/status': typeof MarketingStatusRoute
  '/api/status': typeof ApiStatusRoute
  '/home/achievements': typeof HomeAchievementsRoute
  '/home/checkins': typeof HomeCheckinsRoute
  '/home/insights': typeof HomeInsightsRoute
  '/home/profile': typeof HomeProfileRoute
  '/home/settings': typeof HomeSettingsRoute
  '/home/streaks': typeof HomeStreaksRoute
  '/home/': typeof HomeIndexRoute
  '/home/circles/$circleId': typeof HomeCirclesCircleIdRouteRouteWithChildren
  '/home/habits/$habitId': typeof HomeHabitsHabitIdRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/home/circles/new': typeof HomeCirclesNewRoute
  '/home/habits/archived': typeof HomeHabitsArchivedRoute
  '/home/habits/new': typeof HomeHabitsNewRoute
  '/home/circles/': typeof HomeCirclesIndexRoute
  '/home/habits/': typeof HomeHabitsIndexRoute
  '/home/circles/$circleId/edit': typeof HomeCirclesCircleIdEditRoute
  '/home/circles/join/$code': typeof HomeCirclesJoinCodeRoute
  '/home/habits/$habitId/edit': typeof HomeHabitsHabitIdEditRoute
  '/home/circles/$circleId/': typeof HomeCirclesCircleIdIndexRoute
  '/home/habits/$habitId/': typeof HomeHabitsHabitIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MarketingIndexRoute
  '/login': typeof AuthLoginRoute
  '/about': typeof MarketingAboutRoute
  '/features': typeof MarketingFeaturesRoute
  '/status': typeof MarketingStatusRoute
  '/api/status': typeof ApiStatusRoute
  '/home/achievements': typeof HomeAchievementsRoute
  '/home/checkins': typeof HomeCheckinsRoute
  '/home/insights': typeof HomeInsightsRoute
  '/home/profile': typeof HomeProfileRoute
  '/home/settings': typeof HomeSettingsRoute
  '/home/streaks': typeof HomeStreaksRoute
  '/home': typeof HomeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/home/circles/new': typeof HomeCirclesNewRoute
  '/home/habits/archived': typeof HomeHabitsArchivedRoute
  '/home/habits/new': typeof HomeHabitsNewRoute
  '/home/circles': typeof HomeCirclesIndexRoute
  '/home/habits': typeof HomeHabitsIndexRoute
  '/home/circles/$circleId/edit': typeof HomeCirclesCircleIdEditRoute
  '/home/circles/join/$code': typeof HomeCirclesJoinCodeRoute
  '/home/habits/$habitId/edit': typeof HomeHabitsHabitIdEditRoute
  '/home/circles/$circleId': typeof HomeCirclesCircleIdIndexRoute
  '/home/habits/$habitId': typeof HomeHabitsHabitIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_marketing': typeof MarketingRouteRouteWithChildren
  '/home': typeof HomeRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_marketing/about': typeof MarketingAboutRoute
  '/_marketing/features': typeof MarketingFeaturesRoute
  '/_marketing/status': typeof MarketingStatusRoute
  '/api/status': typeof ApiStatusRoute
  '/home/achievements': typeof HomeAchievementsRoute
  '/home/checkins': typeof HomeCheckinsRoute
  '/home/insights': typeof HomeInsightsRoute
  '/home/profile': typeof HomeProfileRoute
  '/home/settings': typeof HomeSettingsRoute
  '/home/streaks': typeof HomeStreaksRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/home/': typeof HomeIndexRoute
  '/home/circles/$circleId': typeof HomeCirclesCircleIdRouteRouteWithChildren
  '/home/habits/$habitId': typeof HomeHabitsHabitIdRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/home/circles/new': typeof HomeCirclesNewRoute
  '/home/habits/archived': typeof HomeHabitsArchivedRoute
  '/home/habits/new': typeof HomeHabitsNewRoute
  '/home/circles/': typeof HomeCirclesIndexRoute
  '/home/habits/': typeof HomeHabitsIndexRoute
  '/home/circles/$circleId/edit': typeof HomeCirclesCircleIdEditRoute
  '/home/circles/join/$code': typeof HomeCirclesJoinCodeRoute
  '/home/habits/$habitId/edit': typeof HomeHabitsHabitIdEditRoute
  '/home/circles/$circleId/': typeof HomeCirclesCircleIdIndexRoute
  '/home/habits/$habitId/': typeof HomeHabitsHabitIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/login'
    | '/about'
    | '/features'
    | '/status'
    | '/api/status'
    | '/home/achievements'
    | '/home/checkins'
    | '/home/insights'
    | '/home/profile'
    | '/home/settings'
    | '/home/streaks'
    | '/home/'
    | '/home/circles/$circleId'
    | '/home/habits/$habitId'
    | '/api/auth/$'
    | '/home/circles/new'
    | '/home/habits/archived'
    | '/home/habits/new'
    | '/home/circles/'
    | '/home/habits/'
    | '/home/circles/$circleId/edit'
    | '/home/circles/join/$code'
    | '/home/habits/$habitId/edit'
    | '/home/circles/$circleId/'
    | '/home/habits/$habitId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/about'
    | '/features'
    | '/status'
    | '/api/status'
    | '/home/achievements'
    | '/home/checkins'
    | '/home/insights'
    | '/home/profile'
    | '/home/settings'
    | '/home/streaks'
    | '/home'
    | '/api/auth/$'
    | '/home/circles/new'
    | '/home/habits/archived'
    | '/home/habits/new'
    | '/home/circles'
    | '/home/habits'
    | '/home/circles/$circleId/edit'
    | '/home/circles/join/$code'
    | '/home/habits/$habitId/edit'
    | '/home/circles/$circleId'
    | '/home/habits/$habitId'
  id:
    | '__root__'
    | '/_auth'
    | '/_marketing'
    | '/home'
    | '/_auth/login'
    | '/_marketing/about'
    | '/_marketing/features'
    | '/_marketing/status'
    | '/api/status'
    | '/home/achievements'
    | '/home/checkins'
    | '/home/insights'
    | '/home/profile'
    | '/home/settings'
    | '/home/streaks'
    | '/_marketing/'
    | '/home/'
    | '/home/circles/$circleId'
    | '/home/habits/$habitId'
    | '/api/auth/$'
    | '/home/circles/new'
    | '/home/habits/archived'
    | '/home/habits/new'
    | '/home/circles/'
    | '/home/habits/'
    | '/home/circles/$circleId/edit'
    | '/home/circles/join/$code'
    | '/home/habits/$habitId/edit'
    | '/home/circles/$circleId/'
    | '/home/habits/$habitId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  MarketingRouteRoute: typeof MarketingRouteRouteWithChildren
  HomeRouteRoute: typeof HomeRouteRouteWithChildren
  ApiStatusRoute: typeof ApiStatusRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/about': {
      id: '/_marketing/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MarketingAboutRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/features': {
      id: '/_marketing/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof MarketingFeaturesRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_marketing/status': {
      id: '/_marketing/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof MarketingStatusRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/api/status': {
      id: '/api/status'
      path: '/api/status'
      fullPath: '/api/status'
      preLoaderRoute: typeof ApiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/achievements': {
      id: '/home/achievements'
      path: '/achievements'
      fullPath: '/home/achievements'
      preLoaderRoute: typeof HomeAchievementsRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/checkins': {
      id: '/home/checkins'
      path: '/checkins'
      fullPath: '/home/checkins'
      preLoaderRoute: typeof HomeCheckinsRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/insights': {
      id: '/home/insights'
      path: '/insights'
      fullPath: '/home/insights'
      preLoaderRoute: typeof HomeInsightsRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/profile': {
      id: '/home/profile'
      path: '/profile'
      fullPath: '/home/profile'
      preLoaderRoute: typeof HomeProfileRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/settings': {
      id: '/home/settings'
      path: '/settings'
      fullPath: '/home/settings'
      preLoaderRoute: typeof HomeSettingsRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/streaks': {
      id: '/home/streaks'
      path: '/streaks'
      fullPath: '/home/streaks'
      preLoaderRoute: typeof HomeStreaksRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/circles/': {
      id: '/home/circles/'
      path: '/circles'
      fullPath: '/home/circles/'
      preLoaderRoute: typeof HomeCirclesIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/circles/$circleId': {
      id: '/home/circles/$circleId'
      path: '/circles/$circleId'
      fullPath: '/home/circles/$circleId'
      preLoaderRoute: typeof HomeCirclesCircleIdRouteRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/circles/new': {
      id: '/home/circles/new'
      path: '/circles/new'
      fullPath: '/home/circles/new'
      preLoaderRoute: typeof HomeCirclesNewRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/habits/': {
      id: '/home/habits/'
      path: '/habits'
      fullPath: '/home/habits/'
      preLoaderRoute: typeof HomeHabitsIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/habits/$habitId': {
      id: '/home/habits/$habitId'
      path: '/habits/$habitId'
      fullPath: '/home/habits/$habitId'
      preLoaderRoute: typeof HomeHabitsHabitIdRouteRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/habits/archived': {
      id: '/home/habits/archived'
      path: '/habits/archived'
      fullPath: '/home/habits/archived'
      preLoaderRoute: typeof HomeHabitsArchivedRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/habits/new': {
      id: '/home/habits/new'
      path: '/habits/new'
      fullPath: '/home/habits/new'
      preLoaderRoute: typeof HomeHabitsNewRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/circles/$circleId/': {
      id: '/home/circles/$circleId/'
      path: '/'
      fullPath: '/home/circles/$circleId/'
      preLoaderRoute: typeof HomeCirclesCircleIdIndexRouteImport
      parentRoute: typeof HomeCirclesCircleIdRouteRoute
    }
    '/home/circles/$circleId/edit': {
      id: '/home/circles/$circleId/edit'
      path: '/edit'
      fullPath: '/home/circles/$circleId/edit'
      preLoaderRoute: typeof HomeCirclesCircleIdEditRouteImport
      parentRoute: typeof HomeCirclesCircleIdRouteRoute
    }
    '/home/circles/join/$code': {
      id: '/home/circles/join/$code'
      path: '/circles/join/$code'
      fullPath: '/home/circles/join/$code'
      preLoaderRoute: typeof HomeCirclesJoinCodeRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/habits/$habitId/': {
      id: '/home/habits/$habitId/'
      path: '/'
      fullPath: '/home/habits/$habitId/'
      preLoaderRoute: typeof HomeHabitsHabitIdIndexRouteImport
      parentRoute: typeof HomeHabitsHabitIdRouteRoute
    }
    '/home/habits/$habitId/edit': {
      id: '/home/habits/$habitId/edit'
      path: '/edit'
      fullPath: '/home/habits/$habitId/edit'
      preLoaderRoute: typeof HomeHabitsHabitIdEditRouteImport
      parentRoute: typeof HomeHabitsHabitIdRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface MarketingRouteRouteChildren {
  MarketingAboutRoute: typeof MarketingAboutRoute
  MarketingFeaturesRoute: typeof MarketingFeaturesRoute
  MarketingStatusRoute: typeof MarketingStatusRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteRouteChildren: MarketingRouteRouteChildren = {
  MarketingAboutRoute: MarketingAboutRoute,
  MarketingFeaturesRoute: MarketingFeaturesRoute,
  MarketingStatusRoute: MarketingStatusRoute,
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteRouteWithChildren = MarketingRouteRoute._addFileChildren(
  MarketingRouteRouteChildren,
)

interface HomeCirclesCircleIdRouteRouteChildren {
  HomeCirclesCircleIdEditRoute: typeof HomeCirclesCircleIdEditRoute
  HomeCirclesCircleIdIndexRoute: typeof HomeCirclesCircleIdIndexRoute
}

const HomeCirclesCircleIdRouteRouteChildren: HomeCirclesCircleIdRouteRouteChildren =
  {
    HomeCirclesCircleIdEditRoute: HomeCirclesCircleIdEditRoute,
    HomeCirclesCircleIdIndexRoute: HomeCirclesCircleIdIndexRoute,
  }

const HomeCirclesCircleIdRouteRouteWithChildren =
  HomeCirclesCircleIdRouteRoute._addFileChildren(
    HomeCirclesCircleIdRouteRouteChildren,
  )

interface HomeHabitsHabitIdRouteRouteChildren {
  HomeHabitsHabitIdEditRoute: typeof HomeHabitsHabitIdEditRoute
  HomeHabitsHabitIdIndexRoute: typeof HomeHabitsHabitIdIndexRoute
}

const HomeHabitsHabitIdRouteRouteChildren: HomeHabitsHabitIdRouteRouteChildren =
  {
    HomeHabitsHabitIdEditRoute: HomeHabitsHabitIdEditRoute,
    HomeHabitsHabitIdIndexRoute: HomeHabitsHabitIdIndexRoute,
  }

const HomeHabitsHabitIdRouteRouteWithChildren =
  HomeHabitsHabitIdRouteRoute._addFileChildren(
    HomeHabitsHabitIdRouteRouteChildren,
  )

interface HomeRouteRouteChildren {
  HomeAchievementsRoute: typeof HomeAchievementsRoute
  HomeCheckinsRoute: typeof HomeCheckinsRoute
  HomeInsightsRoute: typeof HomeInsightsRoute
  HomeProfileRoute: typeof HomeProfileRoute
  HomeSettingsRoute: typeof HomeSettingsRoute
  HomeStreaksRoute: typeof HomeStreaksRoute
  HomeIndexRoute: typeof HomeIndexRoute
  HomeCirclesCircleIdRouteRoute: typeof HomeCirclesCircleIdRouteRouteWithChildren
  HomeHabitsHabitIdRouteRoute: typeof HomeHabitsHabitIdRouteRouteWithChildren
  HomeCirclesNewRoute: typeof HomeCirclesNewRoute
  HomeHabitsArchivedRoute: typeof HomeHabitsArchivedRoute
  HomeHabitsNewRoute: typeof HomeHabitsNewRoute
  HomeCirclesIndexRoute: typeof HomeCirclesIndexRoute
  HomeHabitsIndexRoute: typeof HomeHabitsIndexRoute
  HomeCirclesJoinCodeRoute: typeof HomeCirclesJoinCodeRoute
}

const HomeRouteRouteChildren: HomeRouteRouteChildren = {
  HomeAchievementsRoute: HomeAchievementsRoute,
  HomeCheckinsRoute: HomeCheckinsRoute,
  HomeInsightsRoute: HomeInsightsRoute,
  HomeProfileRoute: HomeProfileRoute,
  HomeSettingsRoute: HomeSettingsRoute,
  HomeStreaksRoute: HomeStreaksRoute,
  HomeIndexRoute: HomeIndexRoute,
  HomeCirclesCircleIdRouteRoute: HomeCirclesCircleIdRouteRouteWithChildren,
  HomeHabitsHabitIdRouteRoute: HomeHabitsHabitIdRouteRouteWithChildren,
  HomeCirclesNewRoute: HomeCirclesNewRoute,
  HomeHabitsArchivedRoute: HomeHabitsArchivedRoute,
  HomeHabitsNewRoute: HomeHabitsNewRoute,
  HomeCirclesIndexRoute: HomeCirclesIndexRoute,
  HomeHabitsIndexRoute: HomeHabitsIndexRoute,
  HomeCirclesJoinCodeRoute: HomeCirclesJoinCodeRoute,
}

const HomeRouteRouteWithChildren = HomeRouteRoute._addFileChildren(
  HomeRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  MarketingRouteRoute: MarketingRouteRouteWithChildren,
  HomeRouteRoute: HomeRouteRouteWithChildren,
  ApiStatusRoute: ApiStatusRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
